// SPDX-License-Identifier: UNLICENSED
/// @author @HardlyCodeMan https://github.com/HardlyCodeMan/audit_helper/
/// @info Boilerplate test file auto generated by Solidity Contract Audit Helper v0.07
pragma solidity ^0.8.0;

import "forge-std/Test.sol";

contract RecoveryTest is Test { 
	function setUp() public {

	}
	function testGeneratetoken(string memory _name, uint256 _initialSupply) public { 
 
	}

contract SimpleTokenTest is Test { 
	function setUp() public {

	}
	function testTransfer(address _to, uint _amount) public { 
 
	}
	function testDestroy(address payable _to) public { 
 
	}

}