// SPDX-License-Identifier: UNLICENSED
/// @author @HardlyCodeMan https://github.com/HardlyCodeMan/audit_helper/
/// @info Boilerplate test file auto generated by Solidity Contract Audit Helper v0.0.8
pragma solidity ^0.8.0;

import "forge-std/Test.sol";
import "src/GatekeeperTwo.sol";

contract GatekeeperTwoTest is Test { 
	GatekeeperTwo gates = GatekeeperTwo(0xb861FDB2b3399D084AE6BE50beDf78d80D0109A8);
    address public player = 0x8656D273630865bB4887E00d86a338A214Ac4b50;

    function setUp() public {

	}
	function testEnter(bytes8 _gateKey) public { 
 
	}

}