// SPDX-License-Identifier: UNLICENSED
/// @author @HardlyCodeMan https://github.com/HardlyCodeMan/audit_helper/
/// @info Boilerplate test file auto generated by Solidity Contract Audit Helper v0.0.8
pragma solidity 0.8.17;

import "forge-std/Test.sol";
import "../src/HackGates.sol";

contract HackGatesTest is Test { 
	function setUp() public {

	}

}