// SPDX-License-Identifier: UNLICENSED
/// @author @HardlyCodeMan https://github.com/HardlyCodeMan/audit_helper/
/// @info Boilerplate test file auto generated by Solidity Contract Audit Helper v0.07
pragma solidity ^0.8.0;

import "forge-std/Test.sol";
import "openzeppelin-contracts/token/ERC20/IERC20.sol";
import "openzeppelin-contracts/token/ERC20/ERC20.sol";
import 'openzeppelin-contracts/access/Ownable.sol';

contract DexTest is Test, Ownable { 
	function setUp() public {

	}
	function testSettokens(address _token1, address _token2) public onlyOwner { 
 
	}
	function testAddliquidity(address token_address, uint amount) public onlyOwner { 
 
	}
	function testSwap(address from, address to, uint amount) public { 
 
	}
	function testGetswapprice(address from, address to, uint amount) public view returns(uint){ 
 
	}
	function testApprove(address spender, uint amount) public { 
 
	}
	function testBalanceof(address token, address account) public view returns (uint){ 
 
	}
	function testApprove(address owner, address spender, uint256 amount) public { 
 
	}
}