// SPDX-License-Identifier: UNLICENSED
/// @author @HardlyCodeMan https://github.com/HardlyCodeMan/audit_helper/
/// @info Boilerplate test file auto generated by Solidity Contract Audit Helper v0.07
pragma solidity ^0.8.0;

import "forge-std/Test.sol";

contract MagicNumTest is Test { 
	function setUp() public {

	}
	function testSetsolver(address _solver) public { 
 
	}

}