// SPDX-License-Identifier: UNLICENSED
/// @author @HardlyCodeMan https://github.com/HardlyCodeMan/audit_helper/
/// @info Boilerplate test file auto generated by Solidity Contract Audit Helper v0.07
pragma solidity 0.8.17;

import "forge-std/Test.sol";
import "../src/Shop.sol";
import "../src/HackShop.sol";

contract HackShopTest is Test { 
	HackShop hack;
	Shop shop;
	address user;

	function setUp() public {
		user = address(0xB3ef);
		shop = new Shop();
		hack = new HackShop(shop);
	}

	function testExploit() public { 
		vm.startPrank(user);
		
		console.log("Price: %i isSold: ", shop.price(), shop.isSold());
		assertEq(shop.price(), 100, "");
		assertEq(shop.isSold(), false, "");

		hack.exploit();
		console.log("Price: %i isSold: ", shop.price(), shop.isSold());
		assertEq(shop.price(), 1, "");
		assertEq(shop.isSold(), true, "");

		vm.stopPrank();
	}

}